// Terms of Service Page for Morgus
import { Link } from 'react-router-dom';
import './Legal.css';

export function Terms() {
  return (
    <div className="legal-container">
      <div className="legal-card">
        <Link to="/" className="legal-back">← Back to Morgus</Link>
        
        <div className="legal-header">
          <div className="legal-logo">
            <span className="logo-icon">🐷</span>
            <span className="logo-text">Morgus</span>
          </div>
          <h1>Terms of Service</h1>
          <p className="legal-updated">Last updated: December 20, 2025</p>
        </div>

        <div className="legal-content">
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using Morgus ("the Service"), you agree to be bound by these Terms of Service. 
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              Morgus is an AI-powered assistant platform that provides various capabilities including but not limited to:
            </p>
            <ul>
              <li>Natural language processing and conversation</li>
              <li>Document generation and analysis</li>
              <li>Image generation and processing</li>
              <li>Web research and data retrieval</li>
              <li>Code generation and technical assistance</li>
            </ul>
          </section>

          <section>
            <h2>3. User Accounts</h2>
            <p>
              To access certain features of the Service, you must create an account. You agree to:
            </p>
            <ul>
              <li>Provide accurate and complete registration information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized access</li>
              <li>Accept responsibility for all activities under your account</li>
            </ul>
          </section>

          <section>
            <h2>4. Subscription Plans</h2>
            <p>
              Morgus offers various subscription tiers including free and paid plans. Paid subscriptions are billed 
              according to the plan selected. You may cancel your subscription at any time, but refunds are provided 
              only as required by applicable law.
            </p>
            <h3>4.1 Day Passes</h3>
            <p>
              Day passes provide temporary access to premium features. Day passes expire 24 hours after activation 
              and are non-refundable.
            </p>
            <h3>4.2 Promo Codes</h3>
            <p>
              Promotional codes may be offered from time to time. These codes are subject to specific terms and 
              expiration dates as indicated at the time of issuance.
            </p>
          </section>

          <section>
            <h2>5. Acceptable Use</h2>
            <p>You agree NOT to use the Service to:</p>
            <ul>
              <li>Violate any applicable laws or regulations</li>
              <li>Generate illegal, harmful, or offensive content</li>
              <li>Infringe on intellectual property rights</li>
              <li>Attempt to gain unauthorized access to systems</li>
              <li>Distribute malware or engage in hacking activities</li>
              <li>Harass, abuse, or harm others</li>
              <li>Generate spam or unsolicited communications</li>
              <li>Impersonate others or misrepresent your identity</li>
            </ul>
          </section>

          <section>
            <h2>6. AI-Generated Content</h2>
            <p>
              Content generated by Morgus is provided "as is" without warranties of accuracy or completeness. 
              You acknowledge that:
            </p>
            <ul>
              <li>AI-generated content may contain errors or inaccuracies</li>
              <li>You are responsible for reviewing and verifying all generated content</li>
              <li>Generated content should not be relied upon for medical, legal, or financial advice</li>
              <li>You retain ownership of content you create using the Service</li>
            </ul>
          </section>

          <section>
            <h2>7. Data and Privacy</h2>
            <p>
              Your use of the Service is also governed by our <Link to="/privacy">Privacy Policy</Link>. 
              By using the Service, you consent to the collection and use of information as described therein.
            </p>
            <h3>7.1 Training Data</h3>
            <p>
              By default, your conversations may be used to improve Morgus. You can opt out of this at any time 
              using the "Don't Train on Me" toggle in Settings.
            </p>
          </section>

          <section>
            <h2>8. Intellectual Property</h2>
            <p>
              The Service, including its design, features, and content (excluding user-generated content), 
              is owned by Morgus and protected by intellectual property laws. You may not copy, modify, 
              or distribute any part of the Service without permission.
            </p>
          </section>

          <section>
            <h2>9. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, MORGUS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, 
              ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2>10. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS 
              OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
              PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </section>

          <section>
            <h2>11. Modifications to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of significant changes 
              via email or through the Service. Continued use after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2>12. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time for violation of these Terms 
              or for any other reason at our discretion. Upon termination, your right to use the Service will 
              immediately cease.
            </p>
          </section>

          <section>
            <h2>13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of California, 
              United States, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2>14. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="contact-info">
              <strong>Email:</strong> legal@morgus.ai<br />
              <strong>Website:</strong> https://morgus.ai
            </p>
          </section>
        </div>

        <div className="legal-footer">
          <Link to="/privacy">Privacy Policy</Link>
          <span>•</span>
          <Link to="/">Return to Morgus</Link>
        </div>
      </div>
    </div>
  );
}
